# Generated by Django 2.0.2 on 2018-02-14 10:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('kotobjy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author_books',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kotobjy.Author')),
                ('book_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kotobjy.Book')),
            ],
        ),
        migrations.AddField(
            model_name='user_fav',
            name='user_id',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='user_fav',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='user_fav',
            name='user_id',
        ),
    ]
