# Generated by Django 2.0.2 on 2018-04-01 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kotobjy', '0002_book_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_books',
            name='review',
            field=models.TextField(max_length=200, null=True),
        ),
    ]
