# Generated by Django 2.0.2 on 2018-02-20 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kotobjy', '0002_auto_20180214_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='pub_date',
            field=models.DateField(verbose_name='date published'),
        ),
    ]
