# Generated by Django 2.0.2 on 2018-04-01 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kotobjy', '0003_auto_20180401_0809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_books',
            name='rate',
            field=models.IntegerField(default=0),
        ),
    ]
