# Generated by Django 2.0.2 on 2018-04-01 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kotobjy', '0005_auto_20180401_0814'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_books',
            name='review',
        ),
    ]
