# Generated by Django 2.0.2 on 2018-04-01 09:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('kotobjy', '0006_remove_user_books_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_books',
            name='user_id',
        ),
        migrations.AddField(
            model_name='user_books',
            name='user_id',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='user_wish_list',
            name='user_id',
        ),
        migrations.AddField(
            model_name='user_wish_list',
            name='user_id',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
