# Generated by Django 2.0.2 on 2018-04-01 09:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('kotobjy', '0007_auto_20180401_0954'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_books',
            name='user_id',
        ),
        migrations.AddField(
            model_name='user_books',
            name='user_id',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='user_wish_list',
            name='user_id',
        ),
        migrations.AddField(
            model_name='user_wish_list',
            name='user_id',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
