# Generated by Django 2.0.2 on 2018-04-04 08:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kotobjy', '0011_auto_20180404_0714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_fav',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
