# Generated by Django 2.0.2 on 2018-04-04 08:25

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kotobjy', '0012_auto_20180404_0824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_fav',
            name='user',
            field=models.ForeignKey(default=django.contrib.auth.models.User, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
